# Pre-commit configuration for Atlas v0.2
# Install: pip install pre-commit && pre-commit install

repos:
  # Python formatter (Black)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--line-length=100"]

  # Linter (Ruff) - disabled for now, too many pre-existing issues
  # Uncomment and fix after merging v0.2 core
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.9
  #   hooks:
  #     - id: ruff
  #       args: ["check", "--fix"]

  # Type checker (mypy) - disabled for now, too many pre-existing type issues
  # Uncomment and fix after merging v0.2 core
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       args: ["--no-error-summary", "--ignore-missing-imports"]
  #       exclude: "^tests/"

  # Trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
